version: '3.8'

services:
  # 1. Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      # Pass the API URL to the build process
      args:
        NEXT_PUBLIC_API_URL: ${DOMAIN_URL}
    image: datronyx-frontend:latest 
    ports:
      - "3000:3000"
    restart: always

  # 2. Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: datronyx_backend
    environment:
      # These now read from your .env file
      - DB_HOST=${MYSQL_HOST}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
    depends_on:
      - db
    image: datronyx-backend:latest
    ports:
      - "8000:8000"
    restart: always

  # 3. Nginx
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    restart: always

  # 4. Database
  db:
    image: mysql:8.0
    container_name: datronyx_db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      # Reading from .env
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always

volumes:
  db_data:
  # 4. MySQL Database
#   db:
#     image: mysql:8.0
#     container_name: datronyx_db
#     command: --default-authentication-plugin=mysql_native_password
#     environment:
#       MYSQL_ROOT_PASSWORD: DepthFirst
#       MYSQL_DATABASE: datronyx_db
#       MYSQL_USER: datronyx_user
#       MYSQL_PASSWORD: datronyx@rahul#ceo//34
#     volumes:
#       - db_data:/var/lib/mysql
#     ports:
#       - "3306:3306"
#     restart: always

# volumes:
#   db_data:
