version: '3.8'

services:
  # 1. Frontend
  frontend:
    image: ghcr.io/rahulkumarsahdepp/datronyx-website/frontend:latest
    container_name: datronyx-frontend
    restart: always
    ports:
      - "3000:3000"

  # 2. Backend
  backend:
    # ‚ùå REMOVED: build context
    image: ghcr.io/rahulkumarsahdepp/datronyx-website/backend:latest
    container_name: datronyx-backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db 
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
    depends_on:
      - db

  # 3. Nginx
  nginx:
    image: ghcr.io/rahulkumarsahdepp/datronyx-website/nginx:latest
    container_name: datronyx-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend

  # 4. Database (Stateful Service)
  db:
    image: mysql:8.0
    container_name: datronyx_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data: